name: Deploy to Vercel

on:
  push:
    branches: []

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: cd 2fa-project && npm install

      - name: Run Lint
        run: cd 2fa-project && npm run lint

      - name: Run Tests
        run: cd 2fa-project && npm test

      - name: Run Build
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          SESSION_PASSWORD: ${{ secrets.SESSION_PASSWORD }}
          NEXT_PUBLIC_APP_URL: ${{ secrets.NEXT_PUBLIC_APP_URL }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          HMAC_SECRET: ${{ secrets.HMAC_SECRET }}
          RECOVERY_CODE_SECRET: ${{ secrets.RECOVERY_CODE_SECRET }}
          NEXT_PUBLIC_RECAPTCHA_SITE_KEY: ${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}
          RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
          SECRET_ENCRYPTION_KEY: ${{secrets.SECRET_ENCRYPTION_KEY}}
        run: cd 2fa-project && npm run build

      - name: Deploy to Vercel
        if: ${{ success() }}
        env:
          VERCEL_DEPLOY_HOOK: ${{ secrets.VERCEL_DEPLOY_HOOK }}
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}"
